import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

// PDF styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    lineHeight: 1.5,
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: "center",
    color: "#0891b2",
  },
  section: {
    marginBottom: 20,
  },
  heading: {
    fontSize: 16,
    marginBottom: 10,
    color: "#06b6d4",
  },
  text: {
    marginBottom: 10,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 10,
    color: "#666",
  },
});

type ComplianceReportProps = {
  analysis: string;
  email: string;
  region: string;
};

export const ComplianceReport = ({ analysis, email, region }: ComplianceReportProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>SecureAudit Compliance Report</Text>
      <View style={styles.section}>
        <Text>User: {email}</Text>
        <Text>Region: {region === "global" ? "Global (SOC 2/ISO)" : region.charAt(0).toUpperCase() + region.slice(1)}</Text>
        <Text>Date: {new Date().toLocaleDateString()}</Text>
      </View>
      <View style={styles.section}>
        <Text style={styles.heading}>Analysis Results</Text>
        <Text style={styles.text}>{analysis}</Text>
      </View>
      <Text style={styles.footer}>Generated by SecureAudit — AI-Powered Compliance for Africa & Beyond</Text>
    </Page>
  </Document>
);